### ISSUE TITLE
Typography Task

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#1]
# Typography Task

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 15th December 11:59 PM**

**The text file is provided in the "Typography Task-1" folder itself.**

*Imagine a dance floor where fonts boogie, dots and commas twirl, and spaces between lines do a graceful dance. Your mission is to sprinkle that typographical magic on this paragraph and make it a reader's delight!*

Typography helps create harmony and consistency in a design. The main purpose of typography is to make it easier to read what you've written: It makes it possible to quickly scan your text. It compels readers to interact with your writing. When done correctly, it strengthens the argument it makes.

> 💡 This task should be done in **Google Docs / Figma**.

If you are unclear with how to start, you can check out these links: 
- [Video on Typography](https://www.youtube.com/watch?v=sByzHoiYFX0)
- [Article on Typography](https://www.youtube.com/watch?v=sByzHoiYFX0)

## Procedure:

1. Skim through the given text ( **in typography.txt file** ) once and define the **Hierarchy** i.e., mark Headings/ Sub-headings/ Important points.
2. Decide the Font/ Type-face you would be using according to the context of the text. You can do font-pairing i.e, use different font for Headings/ Sub-headings but, don't loose the **Consistency**.
3. Check for margins and spacings. The proper use of white space ensures an excellent user experience and a great readability experience. It helps to balance design elements and better organise content to improve the visual communication experience.
4. For Submission you would have to provide the link to the doc file or figma file in a .txt file (Named after your github username).
5. Make sure to keep the file in **"Typography Task"** folder only.

## MDC (Minimum Design Criteria):

You must at least define the Hierarchy for the text. Simply copy and pasting the given text without any improvements would not qualify for MDC.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by shrutikarathi6** [comment]
claim

**Comment by shashank-lol** [comment]
Hi! It's an open for all issue no need to claim
