### ISSUE TITLE
Business Card

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#151]
# Business Card Design

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 20th December 11:59 PM**

*Let's take a trip to the future where you are at a valued position in your favorite company(Or maybe you created your own start-up) but you need a business card that depicts your royalty.* 

In this task you have to create a business card for yourself. You may imagine youself in any company at any position (even a janitor😉).

> 💡 This task should be done in **Adobe Illustrator or Figma**.

## Submission Guideline:

- Submit the illustrator file or a .txt file containing the link of your Figma file.
- Make sure to submit the file under the Folder named _"Business Card"_

> This task is of 20 points

## MDC (Minimum Design Criteria):

Try to make the card minimal. The card should not be similar to the current business card of that company. The card should look professional.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim
