### ISSUE TITLE
Pen Tool Task-2

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#190]
# Pen tool Task-2 

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 22nd December 11:59 P.M.**

_Seems like someone is enjoying the pen tool😏. So Let's increase the complexity this time, with the same rules. Good luck with that!_

In this task, you are supposed to copy the given vector in Illustrator or Figma using the pen tool and submit the Illustrator file (.ai file) or a text file with a Figma link. 

> 💡 This task can be done in **Adobe Illustrator or Figma**.

## Submission Guideline:

- Submit the illustrator file or .txt file containing the figma link in the "Pen tool Task-2" Folder only.

> This task is for **20 points**.

## MDC (Minimum Design Criteria):

In this task you can only submit one PR once submitted you wont get chance to edit. The vector which you are going to copy should look like the vector given. If you are struggling with using the Pen tool then watch the video attached in Discord.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![Untitled](https://github.com/opencodeiiita/Lets-Design-4.0/assets/115364171/10a358d6-3a65-4bde-b86e-859c3f9ef59d)

**Comment by kushal7201** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by shashank-lol** [comment]
This is a open for all issue. No need to claim
