### ISSUE TITLE
Flyer Design

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#226]
# Flyer Design

**COMPETITIVE ISSUE**\
**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 25th December 11:59 P.M.**

*New Year is just around the corner and so are the New Year parties. Well this time you are hosting the party, so let's get the preparation started!*

In this task, you are supposed to design an Flyer for your new year party and submit the Illustrator file (.ai file) or a text file with a Figma link. A sample flyer is attached for your reference

> 💡 This task can be done in Adobe Illustrator or Figma.

## Submission Guideline:

- Submit the illustrator file or .txt file with the figma link in the "Flyer Design" Folder only.

> This task is for 30 points.

## MDC (Minimum Design Criteria):

The flyer should mention the following details - \
Event Name \
Event Date - 31 December \
Event Time -  6:00 PM \
Event Venue - PMC, IIITA \
Your contact details 

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![dd581ef9fa88679fd81c1e2f6e538a7c](https://github.com/opencodeiiita/Lets-Design-4.0/assets/115364171/dff93959-5bb8-471f-b918-61f72dc6c11e)

**Comment by abhisheksharma010** [comment]
Claim

**Comment by shashank-lol** [comment]
This is an open for issue no need to claim
