### ISSUE TITLE
Play with Shapes

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#25]
# Play with shapes-1 

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 16th December 11:59 PM**

*Welcome to the magical world of shapes, where  circles spin, rectangles rock 'n' roll, and triangles tumble. Today, you're not just a designer, you're a ringmaster in this circus of creativity, armed with the mighty Shape Tool. So, buckle up, as you are about to see these shapes go all over your screen.*

In this task you have to use basic shapes like *rectangle, square, circle etc.* to create an interesting vector who’s png file is attached below. All you need to do is to copy that vector exactly same

> 💡 This task should be done in **Adobe Illustrator or Figma**.

## Submission Guideline:

- Submit the illustrator file in the "Play with shape-1" Folder only or Submit a .txt file containing the link of your Figma file.
- Make sure to submit the file under the Folder named **"Play with Shapes"**.
> This task is of 15 points

## MDC (Minimum Design Criteria):

The vector which you are going to copy should look like that.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![aefd672b3d3a48a171a9f90e2fbbd04d](https://github.com/opencodeiiita/Lets-Design-4.0/assets/115364171/eeabb33d-2658-455a-b3fb-3c840900f055)

**Comment by harshchawlachad** [comment]
Claim

**Comment by shashank-lol** [comment]
Hi, this issue is open for all no need to claim
