### ISSUE TITLE
ID card Design

### ISSUE THREAD

**Issue by AyushmanSoni** [opencodeiiita/Lets-Design-4.0#252]
# ID Card Design

**COMPETITIVE ISSUE**\
**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 29th December 05:00 P.M.**

*Well, people were impressed with your flyer and are showing interest in your party. But to keep the party special you have to design ID cards for the guests and youself (Organiser).*

In this task, you are supposed to design ID Cards for 'Guest' and 'Organiser' and submit the Illustrator file (.ai file) or a text file with a Figma link. A sample ID Card is attached for your reference. You may either create two different ID Cards for Organiser and Guest or keep the same.

> 💡 This task can be done in Adobe Illustrator or Figma.

## Submission Guideline:

- Submit the illustrator file or .txt file with the figma link in the "ID Card Design" Folder only.

> This Best design will get 50 points. \
> 2nd will get 30 points. \
> 3rd will get 20 points.

## MDC (Minimum Design Criteria):

The ID Card should mention the following details - \
Event Name \
Postition - 'Organiser' or 'Guest' \
Remember to design both back and front of the ID Card.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
@AyushmanSoni I think you forgot to add the sample ID card

**Comment by Nandinig24** [comment]
Claim

**Comment by AyushmanSoni** [comment]
no need to claim for this issue its for everyone
