### ISSUE TITLE
Sticker Design

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#274]
# Sticker Design

**COMPETITIVE ISSUE**\
**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 3rd December 9:59 A.M.**

*Imagine a cool sticker that screams all things tech. Well now stop imagining and start designing. Make it fun, make it cool, and let your creativity shine. Get ready to slap that sticker on and share your love for tech in the coolest way possible*

In this task, you are supposed to design a sticker related to any technology, tech stack, coding, designing, etc. and submit the Illustrator file (.ai file) or a text file with a Figma link. If you are unclear about how a sticker may look you check the following link for your reference:
- [Sticker](https://in.pinterest.com/search/pins/?q=sticker&rs=typed)

> 💡 This task can be done in Adobe Illustrator or Figma.

## Submission Guideline:

- Submit the illustrator file or .txt file with the figma link in the "Sticker Design" Folder only.

> This best sticker will get 30 points. \
> 2nd will get 20 points. \
> 3rd will get 10 points. \
> 5 points to everyone else.

## MDC (Minimum Design Criteria):

The sticker should only be related to tech or design. You may design multiple stickers and only the best will be considered.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by AnshikaSwirl** [comment]
claim

**Comment by shashank-lol** [comment]
It is an open for all issue no need to claim
