### ISSUE TITLE
Letterhead Design

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#295]
# Letterhead Design

**OPEN FOR ALL ISSUE**\
**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 6th December 5:59 P.M.**

*Opencode has given you all a lot of points, now it's time for you to give it something, a Letterhead. Think about colors, fonts, and how everything will be arranged. This challenge is all about turning a simple page into something that looks great and shows off your personality. !*

In this task, you are supposed to design a Letterhead for Opencode. Submit the Illustrator file (.ai file) or a text file with a Figma link.

> 💡 This task can be done in Adobe Illustrator or Figma.

If you are unclear about letterhead design, you may look [here](https://in.pinterest.com/search/pins/?q=letterhead&rs=typed) for inspiration.

## Submission Guideline:

- Submit the illustrator file or .txt file with the figma link in the "Letterhead Design" Folder only.

> This task is for 15 points. 

## MDC (Minimum Design Criteria):

The dimension should be of A4 size. The Letterhead must include the logo of Opencode, your name, email and contact. After creating the letterhead write in the letterhead with the following details:
- To: shashank-lol
- Designation: Mentor
- Date
- Content of 100 words

You may copy text from www.lipsum.com and paste it in the content. 

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by shashank-lol** [comment]
This is an open for all issue no need to claim
