### ISSUE TITLE
Logo Redesign

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#303]
# Logo Re-Design

**Competitive Issue**\
**No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 9th December 8:59 P.M.**

*Redesign a well-known logo, giving it a fresh, modern, or playful touch while retaining its core identity. Think about colors, shapes, and overall aesthetics that align with the brand but add a new flair. This challenge is all about breathing new life into something iconic.*

In this task, you are supposed to Redesign the logo of **Twitter**. Submit the Illustrator file (.ai file) or a text file with a Figma link.

> 💡 This task can be done in Adobe Illustrator or Figma.

## Submission Guideline:

- Submit the illustrator file or .txt file with the figma link in the "Logo Redesign" Folder only.

> The best design will get 50 points \
> 2nd will get 30 points \
> 3rd will get 20 points \
> Remaining will get 5 or 10 points. 

## MDC (Minimum Design Criteria):

Redesign the blue bird logo and not the X logo. The logo should look different from the blue bird logo.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by kushal7201** [comment]
Claim

**Comment by shashank-lol** [comment]
This open for all issue. No need to claim

**Comment by Apoorv012** [comment]
Could you please wait a 2 hours before closing this?
