### ISSUE TITLE
Pen Tool Task-1

### ISSUE THREAD

**Issue by shashank-lol** [opencodeiiita/Lets-Design-4.0#66]
# Pen tool Task-1 

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 17th December 6:59 P.M.**

*Now that you know shapes(Even if you don't, it doesn't matter) it's time to get introduced to your new friend - **The Pen Tool**, your digital sidekick in the world of design. Think of it as a magical pencil which turns your ideas into reality. So get ready to explore the curvy world with the Pen tool!*

In this task, you are supposed to copy the given vector in Illustrator or Figma using the pen tool and submit the Illustrator file (.ai file) or a text file with a Figma link.

> 💡 This task can be done in **Adobe Illustrator or Figma**.

## Submission Guideline:
- Submit the illustrator file or a .txt file containing the link of your Figma file in the "Pen Tool Task-1" Folder only.
> This task is for 20 points

## MDC (Minimum Design Criteria):

In this task you can only submit **1 PR** once submitted you wont get chance to edit. The vector which you are going to copy should look like the vector given.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![lion-head-logo-simple-vector-21270561](https://github.com/opencodeiiita/Lets-Design-4.0/assets/115364171/35c5d206-a0b5-49cc-a7b1-8b1cff952a24)

**Comment by AngadManroy** [comment]
Claim
